services:
  db:

    image: postgres:latest

    ports:
      - "5432:5432"

    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_username}